name: Build & Run Example

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: bootstrap
      run: wilco/bootstrap example/wilco.cpp
    - name: build
      run: example/wilco build
    - name: run
      run: example/bin/Hello

  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: bootstrap
      run: wilco\bootstrap.bat example\wilco.cpp
    - name: build
      run: example\wilco build
    - name: run
      run: example\bin\Hello
    